---
title: '`r paste("ModelSelection", params$name)`'
author: "Christof"
date: '`r format(Sys.time(), "%d.%m.%Y")`'
output: 
  html_document:
    self_contained: true
    toc: yes
    toc_float: no
    toc_depth: 1
    number_sections: no
    code_folding: hide
params:
  name: DefaultName
  workDirPath: !r getwd()
  overwriteNoFeCsv: false
  dataSetPaths: !r c(
    MixCleaned = "~/cerROOT/variable/dataCntryRegiLaggedCleanClean.csv")
  nRepsFinal: 2
  seClusterVariables: !r c("ID", "theYear")
  lambda: !r seq(0, 1, 0.1)
  nFolds: 10
  cvClusterVariable: theYear
  correlationVariable: "residual"
  hclustMethod: "average"
  hclustCut: 0.5
  timeTrendOrders: !r c(0)
  cumulate: null
  target: log2growth
  predictorList: !r list(
    character(0),
    "tc34kt",
    c("tc34kt", "tc34kt_lag1"))
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  message = FALSE,
  include = TRUE,
  out.width = "100%",
  fig.width = 8, 
  fig.height = 8)
```

**Params** (press show on the right to see the parameters)

```{r PrintParams, class.output="foldable"}
print(params)
```


```{r LoadPackages, include=FALSE}
options(tidyverse.quiet = TRUE)
library(tidyverse)
suppressWarnings(library(kableExtra))
library(cerStatistic)
```


```{r SetFilePaths, include=FALSE}
dataDir <- file.path(params$workDir, paste0(params$name, "_Data"))
csvDir <- file.path(params$workDir, paste0(params$name, "_csv"))
getDataFilePath <- function(dataDir, dataName, feOrder) {
  sprintf("%s/%s_NoFe_%d.csv", dataDir, dataName, feOrder)
}
```


```{r SetFixedEffectVariables, include=FALSE}
fixedEffectList <- lapply(params$timeTrendOrders, \(feOrder) {
  fixedEffects <- c("ID", "theYear")
  if (feOrder > 0) {
    fixedEffects <- c(fixedEffects, "ID:year")
  }
  if (feOrder > 1) {
    fixedEffects <- c(fixedEffects, paste0("ID:year_", 2:feOrder))
  }
  return(fixedEffects)
})
names(fixedEffectList) <- params$timeTrendOrders
```

```{r CollectAllVariableNames, include=FALSE}
allFixedEffects <- 
  fixedEffectList |> 
  unlist() |> 
  unique() |> 
  str_split(":") |> 
  unlist() |> 
  unique()

allPredictors <- unique(unlist(params$predictorList))

variables <- unique(c(
  params$target,
  allPredictors,
  allFixedEffects,
  params$seClusterVariables,
  params$cvClusterVariable,
  "year", "ID"))
```

```{r RemoveFixedEffects, include=FALSE}
if (!dir.exists(dataDir))  dir.create(dataDir)
for (dataName in names(params$dataSetPaths)) {
  anyNoFeFileMissing <- FALSE
  for (feOrder in params$timeTrendOrders) {
    outFilePath <- getDataFilePath(dataDir, dataName, feOrder)
    if (!file.exists(outFilePath) || params$overwriteNoFeCsv) {
      anyNoFeFileMissing <- TRUE
      break
    }
  }
  if (!anyNoFeFileMissing) next
  dataRaw <- 
    read_csv(params$dataSetPaths[[dataName]]) |> 
    select(any_of(variables)) |> 
    mutate(theYear = as.character(year))
  if (max(params$timeTrendOrders) > 1) {
    for (k in 2:max(params$timeTrendOrders)) {
      dataRaw <- 
        dataRaw |> 
        mutate(!!sprintf("year_%d", k) := year^k)
    }
  }
  yearColums <- names(dataRaw) |> str_subset("^year")
  dataRaw <- dataRaw |> select(all_of(variables))
  dataScaled <-
    dataRaw |>
    filter(if_all(where(is.numeric), is.finite)) |> 
    mutate(across(where(is.numeric), ~ (. - mean(.)) / sd(.)))
  for (feOrder in params$timeTrendOrders) {
    outFilePath <- getDataFilePath(dataDir, dataName, feOrder)
    if (file.exists(outFilePath) && !params$overwriteNoFeCsv) next
    dataNoFe <- 
      dataScaled |> 
      removeFixedEffects(fixedEffectList[[as.character(feOrder)]], exclude = yearColums) |> 
      select(-all_of(yearColums))
    write_csv(dataNoFe, outFilePath)
  }
}
```

```{r LoadFeFreeData, include=FALSE}
dataLists <- lapply(
  names(params$dataSetPaths), 
  \(dataName) {
    lapply(
      params$timeTrendOrders, 
      \(feOrder) {
        read_csv(getDataFilePath(dataDir, dataName, feOrder))
      }
    ) |> 
      setNames(sprintf("NoFe%d", params$timeTrendOrders))
  }
) |> 
  setNames(names(params$dataSetPaths))
```



# Data Info

```{r ShowDataInfo}
getDataInfo <- function(data, name) {
  tibble(
    name = name,
    rows = nrow(data),
    cols = ncol(data),
    yearMin = min(data$theYear),
    yearMax = max(data$theYear),
    nRegions = data$ID |> unique() |> length())
}
lapply(names(dataLists), \(nm) {
  getDataInfo(dataLists[[nm]][[1]], nm)
}) |> 
  bind_rows() |> 
  makeTable("Data Info")
```


# Model Selection Analysis {.tabset}

```{r DefineShowModelListSelectionTable, include=FALSE}
showModelListSelectionTable <- function(
    data,
    predictorList,
    target,
    nReps,
    timeTrendOrder,
    csvPath
) {
  tbl <- getModelListSelectionTable(
    data,
    predictorList,
    target,
    nReps,
    nFolds = params$nFolds,
    seFun = buildSeFun(buildClusterFun(params$seClusterVariables), cumulate = params$cumulate),
    coefFun = buildCoefFun(cumulate = params$cumulate),
    timeTrendOrder,
    fitAndPredictFun = fitAndPredictLm.,
    cluster = data[[params$cvClusterVariable]],
    lambda = params$lambda,
    csvPath = csvPath
  )
  cat("\n\n", tbl, "\n\n")
}
```



```{r DefineShowModelSelectionAnalysis, include=FALSE}
showModelSelectionAnalysis <- function(dataName) {
    
  dl <- dataLists[[dataName]]
  
  cat(sprintf("\n\n## %s Data{.tabset}\n\n", dataName))
  
  for (feOrder in params$timeTrendOrders) {
    cat(sprintf("\n\n### Time Trends Order %d\n\n", feOrder))
    noFeName <- sprintf("NoFe%d", feOrder)
    showModelListSelectionTable(
      data = dl[[noFeName]], 
      predictorList = params$predictorList, 
      target = params$target, 
      nReps = params$nRepsFinal,
      timeTrendOrder = feOrder,
      csvPath = file.path(csvDir, paste0(dataName, "_", noFeName, ".csv")))
  }
}
```


```{r RunModelSelectionAnalysisAndShow, results='asis'}
lapply(names(dataLists), showModelSelectionAnalysis) |> invisible()
```



# Correlation Analysis {.tabset}


```{r DefineShowCorrelationAnalysis, include=FALSE}
showCorrelationAnalysis <- function(dataName) {
    
  dl <- dataLists[[dataName]]
  
  cat(sprintf("\n\n## %s Data{.tabset}\n\n", dataName))
  
  for (feOrder in params$timeTrendOrders) {
    
    cat(sprintf("\n\n### Time Trends Order %d{.tabset}\n\n", feOrder))
    noFeName <- sprintf("NoFe%d", feOrder)
    data <- dl[[noFeName]]
    
    for (predictors in params$predictorList) {
      
      predString <- if (length(predictors) > 0) paste(predictors, collapse = ", ") else "Null Model"
      cat("\n\n#### Pred: ", predString, "\n\n")
      corrList <- analyzeCorrelation(
        data, 
        predictors, 
        params$target, 
        variable = params$correlationVariable)
      showCorrelations(
        corrList$corrMatId, 
        corrList$corrMatYear, 
        hclustMethod = params$hclustMethod, 
        hclustCut = params$hclustCut)
      cat("\n\n")
    }
  }
}
```

```{r RunCorrelationAnalysisAndShow, results='asis'}
lapply(names(dataLists), showCorrelationAnalysis) |> invisible()
```


# P-Value Analysis {.tabset}


```{r DefineShowPValueAnalysis, include=FALSE}
showPValueAnalysis <- function(dataName) {
    
  dl <- dataLists[[dataName]]
  
  cat(sprintf("\n\n## %s Data{.tabset}\n\n", dataName))
  
  for (feOrder in params$timeTrendOrders) {
    
    cat(sprintf("\n\n### Time Trends Order %d{.tabset}\n\n", feOrder))
    noFeName <- sprintf("NoFe%d", feOrder)
    data <- dl[[noFeName]]
    
    for (predictors in params$predictorList) {
      
      predString <- if (length(predictors) > 0) paste(predictors, collapse = ", ") else "Null Model"
      cat("\n\n#### Pred: ", predString, "\n\n")
      tbl <- getPValueTable(data, predictors, params$target, feOrder, cumulate = params$cumulate)
      if (is.null(tbl)) {
        cat("No predictors, hence no p-Values.\n\n") 
      } else {
        cat("\n\n", tbl, "\n\n")
      }
    }
  }
}
```

```{r RunPValueAnalysisAndShow, results='asis'}
lapply(names(dataLists), showPValueAnalysis) |> invisible()
```
